version: '3'
services:
  wordpress:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./wp:/var/www/html
    ports:
      - "0.0.0.0:80:80"
    restart: always
